sudo: false

dist: xenial
language: python

python:
  - 3.5

env:
  - TOXENV=django111
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22
  - TOXENV=quality

matrix:
 include:
  - python: 2.7
    env: TOXENV=django111

cache:
  - pip

install:
  - pip install -U pip wheel codecov
  - pip install -r requirements/travis.txt

script:
  - make test

after_success:
  codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: dLYdt8dZKsqaYsyZu630xtP8itgthOtRlj9X/hZY10yKTgBGrJeDEkd6bac/Bf17jr5242oanWfsbABAJ18noB1wdeutBTOyFCTwU4glR5ZbZpJnsIJ8fZf2LB14E62NhW8AJyb2ZHJ+Fyt7LXJZYaByXDHEtIlukulwriUA72M=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: '$TOXENV = django111'
