sudo: false

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django110
  - TOXENV=django111

matrix:
 include:
  - python: 3.5
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=django111

cache:
  - pip

install:
  - pip install -U pip wheel codecov
  - make requirements

script:
  - make test

after_success:
  codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: dLYdt8dZKsqaYsyZu630xtP8itgthOtRlj9X/hZY10yKTgBGrJeDEkd6bac/Bf17jr5242oanWfsbABAJ18noB1wdeutBTOyFCTwU4glR5ZbZpJnsIJ8fZf2LB14E62NhW8AJyb2ZHJ+Fyt7LXJZYaByXDHEtIlukulwriUA72M=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
    condition: '$TOXENV = django111'
