[tox]
envlist = django52,quality,check_keywords
requires =
    tox-uv>=1

[pycodestyle]
max-line-length = 120

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    pytest {posargs}

[testenv:quality]
dependency_groups = quality
commands =
    pycodestyle --config=.pep8 src/auth_backends
    pylint --rcfile=pylintrc src/auth_backends

[testenv:check_keywords]
dependency_groups = test
commands =
    python manage.py check_reserved_keywords --override_file db_keyword_overrides.yml
