#check package-lock file version

name: ASCII check

on:
  push:
    branches:
    - 'master'
  pull_request:

jobs:
  ascii-check:
    runs-on:  ubuntu-20.04
    outputs:
      output1: ${{ steps.getversion.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get non-ascii characters
      id: getascii
      run: grep -P "[^\x00-\x7F]" setup.cfg
      
#    - name: check value
#      if: ${{ steps.getascii.outputs.version == null }}
#      run: |
#        echo "ERROR: Outdated package-lock file. Use NPM8 to install dependencies "
#        exit 1
